---
apiVersion: v1
data:
  production.yaml: |
    CLIENT_ID: "{{ .client_id }}"
    CLIENT_SECRET: "{{ .client_secret }}"
    CALLBACK: {{ .url }}/callback
    HOME: {{ .url }}/user
    REDIS_HOST: "redis-cache:6379"
    REDIS_KEY: "{{ .redis_key }}"
kind: ConfigMap
metadata:
  name: mygo
  namespace: haugom
