---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygo
  namespace: haugom
  labels:
    app: mygo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mygo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mygo
    spec:
      containers:
      - name: mygo
        image: haugom/mygo:{{ .image_tag }}
        imagePullPolicy: Always
        args: ["-e", "production"]
        ports:
        - containerPort: 3001
        - containerPort: 8081
        volumeMounts:
          - name: config-vol
            mountPath: /app/config
        resources:
          requests:
            memory: "24Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      volumes:
        - name: config-vol
          configMap:
            name: mygo
