---
kind: Service
apiVersion: v1
metadata:
  name: mygo
  namespace: haugom
spec:
  selector:
    app: mygo
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 3001
  - protocol: TCP
    name: debug
    port: 2345
